### ISSUE TITLE
webgl

### ISSUE THREAD

**Issue by matrix3d** [game-ci/unity-builder#200]
https://github.com/matrix3d/buildu3d/actions/runs/493882061

**Comment by webbertakken** [comment]
Could you please provide more information than just a link, and describe your issue according to the bug report template?

**Comment by matrix3d** [comment]
I'm not sure where the problem is, it may be that this caused the compilation to fail
```
/opt/unity/Editor/Data/il2cpp/build/BeeSettings/offline/bee.exe exited after 48194 ms.
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Unity.IL2CPP.Shell.SetupAndStart(ExecuteContext context, Boolean asyncMode) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 423
   at Unity.IL2CPP.Shell.ExecuteAsync(ExecuteArgs executeArgs, IExecuteController controller, Boolean asyncMode) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 299
   at Unity.IL2CPP.Shell.Execute(ExecuteArgs executeArgs, IExecuteController controller) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 355
   at Unity.IL2CPP.Building.CppProgramBuilder.ProvideObjectFile(IntermediateObjectFileCompilationData data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 334
   at Unity.IL2CPP.Building.ParallelFor.<>c__DisplayClass1_0`2.<RunWithResult>b__0(Object o) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Building/ParallelFor.cs:line 73
```

**Comment by matrix3d** [comment]
https://github.com/matrix3d/buildu3d/runs/1722237537?check_suite_focus=true#step:5:18459

**Comment by matrix3d** [comment]
I will close this bug first and find the real reason

**Comment by addybongo** [comment]
I have this exact same issue, did you find a solution @matrix3d ?

**Comment by GabLeRoux** [comment]
Depending on the used docker image, webgl might not be supported. From the above github-actions log, used docker image was this one:

```
unityci/editor:2020.2.1f1-webgl-0
```

Right now, latest published docker image for `unityci/editor` is `v0.8` as shown here:  
https://github.com/game-ci/docker/releases

This version currently doesn't support webgl due to the following upstream issue:  
https://github.com/game-ci/docker/pull/61

As you can see, it closed, but new images are not published yet. WebGL support is planned for `v1.0` and once we confirmed that it's working, we will publish the new version of the images.

**Comment by addybongo** [comment]
Thanks for the quick response @GabLeRoux ! When exactly will 0.9 be released? I was hoping there'd be a workaround in the meantime while waiting

**Comment by GabLeRoux** [comment]
If you absolutely need to have a fix right now, you can clone https://github.com/game-ci/docker/, build the image for your specific Unity version and publish it to your personal docker hub account and point `unity-builder` to use your custom docker image and report back to https://github.com/game-ci/docker/pull/61

**Comment by addybongo** [comment]
Ahh ok I will look into that thank you :)

**Comment by webbertakken** [comment]
Update: https://github.com/game-ci/docker/releases/tag/v0.9. Let us know if that works for you. 

(please allow ~24 hours for all images to finish building)

**Comment by addybongo** [comment]
@webbertakken working perfectly now thanks! Wish I waited instead of trying to get my own docker build to work for the last 3 hours haha

**Comment by GabLeRoux** [comment]
Turns out Webber had some time today and went ahead with the release :tada:.  
Glad to know it works!

**Comment by matrix3d** [comment]
I have not resolved this. It's just a bug in urp water, and has nothing to do with github action

**Comment by GabLeRoux** [comment]
Note that github-actions builds using `-nographics`.
