### ISSUE TITLE
Segmentation fault in "Testing in COMBINE_RESULTS", later "Caught fatal signal - signo:11 code:1 errno:0"

### ISSUE THREAD

**Issue by achimmihca** [game-ci/unity-builder#522]
**Bug description**

Unity crashes in my test build for Linux when shutting down.
The build finishes fine for Android and iOS.

Not sure if this is related to Unity or the GitHub Action.
Log file is attached.

Interestingly, the tests seem to finish mostly. Then there is a "Segmentation fault" but it continues

```
2023-03-16T10:19:55.6642432Z ###########################
2023-03-16T10:19:55.6642687Z #   Testing in COMBINE_RESULTS  #
2023-03-16T10:19:55.6642903Z ###########################
2023-03-16T10:19:55.6642910Z 
2023-03-16T12:07:07.1370084Z Segmentation fault (core dumped)
2023-03-16T12:07:07.1480815Z Unity Editor version:    2022.2.10f1 (bcebec703747)
2023-03-16T12:07:07.1485026Z Branch:                  2022.2/staging
2023-03-16T12:07:07.1485841Z Build type:              Release
2023-03-16T12:07:07.1486389Z Batch mode:              YES
2023-03-16T12:07:07.1486929Z System name:             Linux
2023-03-16T12:07:07.1487840Z Distro version:          #41-Ubuntu SMP Fri Feb 10 19:59:45 UTC 2023
2023-03-16T12:07:07.1531039Z Kernel version:          5.15.0-1034-azure
2023-03-16T12:07:07.1531633Z Architecture:            x86_64
2023-03-16T12:07:07.1532207Z Available memory:        6943 MB
2023-03-16T12:07:07.1533045Z [Licensing::Module] Trying to connect to existing licensing client channel...

...
```

Later, it crashes completely:

```
2023-03-16T12:07:07.1939887Z Batchmode quit successfully invoked - shutting down!
2023-03-16T12:07:07.1940587Z Curl error 42: Callback aborted
2023-03-16T12:07:07.1941291Z [Licensing::IpcConnector] License Notification channel disconnected successfully.
2023-03-16T12:07:07.1942182Z [Licensing::IpcConnector] License Client channel disconnected successfully.
2023-03-16T12:07:07.1943221Z [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
2023-03-16T12:07:07.1943958Z       Application is shutting down...
2023-03-16T12:07:07.1944887Z [40m[32minfo[39m[22m[49m: Unity.ILPP.Runner.PostProcessingAssemblyLoadContext[0]
2023-03-16T12:07:07.1945712Z       ALC ILPP context 1 is unloading
2023-03-16T12:07:07.1946537Z Caught fatal signal - signo:11 code:1 errno:0 addr:0x4140
2023-03-16T12:07:07.1947380Z Caught fatal signal - signo:11 code:1 errno:0 addr:0x7f5f48000fec
[above message repeated a lot]
2023-03-16T12:07:10.3360865Z Caught fatal signal - signo:11 code:128 errno:0 addr:(nil)
2023-03-16T12:07:10.3361107Z Unexpected exit code 139
2023-03-16T12:07:10.3361124Z 
2023-03-16T12:07:10.3361354Z ###########################
2023-03-16T12:07:10.3361618Z #    COMBINE_RESULTS Results    #
2023-03-16T12:07:10.3361835Z ###########################
2023-03-16T12:07:10.3361908Z 
2023-03-16T12:07:10.3362371Z chmod: cannot access '/github/workspace/CodeCoverage': No such file or directory
2023-03-16T12:07:10.3362814Z Changing to "/github/workspace/_activate-license" directory.
2023-03-16T12:07:10.3363187Z /github/workspace/_activate-license /github/workspace
2023-03-16T12:07:10.3363402Z /github/workspace
2023-03-16T12:07:10.3363410Z 
2023-03-16T12:07:10.3363624Z ###########################
2023-03-16T12:07:10.3363848Z #         Failure         #
2023-03-16T12:07:10.3364061Z ###########################
```

**How to reproduce**

- Run the [GitHub Actions build](https://github.com/UltraStar-Deluxe/Play/actions/runs/4427679072) of [UltraStar Play](https://github.com/UltraStar-Deluxe/Play) (branch "anst/ui-redesign-complete")

**Expected behavior**

The build should finish cleanly.

**Additional details**

See attached log file

[build-log.log](https://github.com/game-ci/unity-builder/files/10990951/build-log.log)

**Comment by achimmihca** [comment]
I have a slightly more helpful error message when doing the build with Windows target platform:

```
2023-03-16T13:10:30.3442240Z Batchmode quit successfully invoked - shutting down!
2023-03-16T13:10:30.3442849Z Curl error 42: Callback aborted
2023-03-16T13:10:30.3443549Z [Licensing::IpcConnector] License Notification channel disconnected successfully.
2023-03-16T13:10:30.3444339Z [Licensing::IpcConnector] License Client channel disconnected successfully.
2023-03-16T13:10:30.3445129Z [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
2023-03-16T13:10:30.3445768Z       Application is shutting down...
2023-03-16T13:10:30.3446600Z [40m[32minfo[39m[22m[49m: Unity.ILPP.Runner.PostProcessingAssemblyLoadContext[0]
2023-03-16T13:10:30.3447331Z       ALC ILPP context 1 is unloading
2023-03-16T13:10:30.3448031Z Caught fatal signal - signo:11 code:1 errno:0 addr:0x80
2023-03-16T13:10:30.3448629Z Obtained 25 stack frames.
2023-03-16T13:10:30.3449255Z #0  0x005627dd3e010c in burst_signal_handler(int, siginfo_t*, void*)
2023-03-16T13:10:30.3449948Z #1  0x007f76129d2980 in funlockfile
2023-03-16T13:10:30.3450599Z #2  0x005627dd3dc245 in lane_allocator::lane_allocator(ujob_control_t*)
2023-03-16T13:10:30.3451570Z #3  0x005627dd3dbef1 in ujob_schedule_parallel_for_internal(ujob_control_t*, JobsCallbackFunctions&, void*, WorkStealingRange*, unsigned int, unsigned int, ujob_handle_t const*, int, unsigned char)
2023-03-16T13:10:30.3452576Z #4  0x005627dd3dd3ca in ujob_schedule_single(ujob_control_t*, void (*)(void*), void*, ujob_handle_t const*, int)
2023-03-16T13:10:30.3453442Z #5  0x005627dd3da4ff in JobQueue::ScheduleJob(void (*)(void*), void*, JobGroupID, JobQueue::JobQueuePriority)
2023-03-16T13:10:30.3454433Z #6  0x005627dd3c8d67 in BackgroundJobQueue::ScheduleJobInternal(void (*)(void*), void*, BackgroundJobQueue::JobFence const&, JobQueue::JobQueuePriority)
2023-03-16T13:10:30.3455288Z #7  0x005627dd0c1a8a in InitialiseBurstDebugDomain()
2023-03-16T13:10:30.3456059Z #8  0x007f7524dad4e7 in MonoDebuggerHandling::RequestFlushClientDebuggerKnowledge()
2023-03-16T13:10:30.3456900Z #9  0x007f7524dadb0c in MonoDebuggerHandling::ProcessLibraryMetadata(void*)
2023-03-16T13:10:30.3457563Z #10 0x00000041c7b3d7 in (Unknown)
2023-03-16T13:10:30.3458104Z #11 0x00000040517b8a in (Unknown)
2023-03-16T13:10:30.3458627Z #12 0x00000040507578 in (Unknown)
2023-03-16T13:10:30.3459140Z #13 0x00000041c69f94 in (Unknown)
2023-03-16T13:10:30.3459651Z #14 0x00000041c69146 in (Unknown)
2023-03-16T13:10:30.3460148Z #15 0x00000041c68834 in (Unknown)
2023-03-16T13:10:30.3460710Z #16 0x007f755045d2d8 in mono_get_runtime_build_info
2023-03-16T13:10:30.3461318Z #17 0x007f75505fcc0a in mono_runtime_invoke
2023-03-16T13:10:30.3461930Z #18 0x007f75505fe4c0 in mono_runtime_delegate_invoke
2023-03-16T13:10:30.3462599Z #19 0x007f755061bec1 in mono_thread_has_sufficient_execution_stack
2023-03-16T13:10:30.3463345Z #20 0x007f755061bd0a in mono_thread_has_sufficient_execution_stack
2023-03-16T13:10:30.3464145Z #21 0x007f7550695430 in GC_inner_start_routine
2023-03-16T13:10:30.3464744Z #22 0x007f75506950c3 in GC_start_routine
2023-03-16T13:10:30.3465311Z #23 0x007f76129c76db in start_thread
2023-03-16T13:10:30.3465870Z #24 0x007f76126f061f in clone
2023-03-16T13:10:30.3466410Z Unexpected exit code 139
```

I guess it is a Unity bug, maybe related to https://issuetracker.unity3d.com/issues/linux-editor-crashes-on-burst-signal-handler-when-universal-rp-camera-is-selected (although this should be fixed long ago).

We just switched to URP and now this issue occurs in the GitHub Actions build.

**Comment by achimmihca** [comment]
I only have this issue when building via GitHub Actions. On my local Ubuntu machine, the build works fine.
